server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:keystore/site.p12"
    key-store-password: password
    key-alias: site
  servlet:
    session:
      timeout: 15m


http.port: 8080

spring:
  application.name: vaccine-portal

  datasource:
    url: "jdbc:mysql://localhost:3306/vaccine"
    username: root
    password: R5aS#C4b&NB$?@6y

  jpa.hibernate.ddl-auto: update

portal:
  admin.password: password

logging.level.root: debug

security:
  require-ssl: true
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8083/auth/realms/baeldung
        jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs




