server:
  port: 8443
  ssl:
    enabled: true
    key-store: "classpath:keystore/site.p12"
    key-store-password: password
    key-alias: site


http.port: 8080

spring:
  application.name: vaccine-portal

  datasource:
    url: "jdbc:mysql://localhost:3306/vaccine"
    username: root
    password: example

  jpa.hibernate.ddl-auto: update

portal:
  admin.password: password

logging.level.root: debug

security:
  require-ssl: true



